import "./globals.css";
import { Barlow_Condensed, Bellefair } from "next/font/google";
import type { Metadata } from "next";

const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow",
});

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bellefair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${barlow.variable} ${bellefair.variable}`}>
      <body>{children}</body>
    </html>
  );
}
